_wandb:
    value:
        cli_version: 0.23.1
        e:
            uvhu83pnabrr2cm5mae1xiwqgn0i9bid:
                codePath: g:\My Drive\Hands-on-CV-Project2\notebooks\04_final_assessmen.ipynb
                codePathLocal: 04_final_assessmen.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "510455517184"
                        used: "424525967360"
                email: constantin.auga@gmx.de
                executable: c:\Users\const\anaconda3\python.exe
                git:
                    commit: 2736d59f81114be438d29b26249065b5aa807f71
                    remote: https://github.com/Conscht/CLIP-Multimodal-Learning.git
                host: Conscht
                memory:
                    total: "16542097408"
                os: Windows-10-10.0.26100-SP0
                program: g:\My Drive\Hands-on-CV-Project2\notebooks\04_final_assessmen.ipynb
                python: CPython 3.11.4
                root: g:\My Drive\Hands-on-CV-Project2\notebooks
                startedAt: "2025-12-31T14:53:45.452279Z"
                writerId: uvhu83pnabrr2cm5mae1xiwqgn0i9bid
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 53
                - 54
            "2":
                - 1
                - 5
                - 53
                - 54
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.4
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
batch_size:
    value: 32
emb:
    value: 200
epochs:
    value: 20
lr:
    value: 0.001
normalize_embeddings:
    value: true
pool_type:
    value: maxpool
stage:
    value: contrastive
task:
    value: 5
temperature:
    value: 0.07
