_wandb:
    value:
        cli_version: 0.23.1
        e:
            z4pgsy1d5ys0cno7dtp3pwovxvnf2o0m:
                codePath: g:\My Drive\Hands-on-CV-Project2\notebooks\04_final_assessmen.ipynb
                codePathLocal: 04_final_assessmen.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "510455517184"
                        used: "432310308864"
                email: constantin.auga@gmx.de
                executable: c:\Users\const\anaconda3\python.exe
                git:
                    commit: 2736d59f81114be438d29b26249065b5aa807f71
                    remote: https://github.com/Conscht/CLIP-Multimodal-Learning.git
                host: Conscht
                memory:
                    total: "16542097408"
                os: Windows-10-10.0.26100-SP0
                program: g:\My Drive\Hands-on-CV-Project2\notebooks\04_final_assessmen.ipynb
                python: CPython 3.11.4
                root: g:\My Drive\Hands-on-CV-Project2\notebooks
                startedAt: "2025-12-31T15:38:59.443331Z"
                writerId: z4pgsy1d5ys0cno7dtp3pwovxvnf2o0m
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 53
                - 54
            "2":
                - 1
                - 5
                - 53
                - 54
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.4
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
dim:
    value: 200
encoders_frozen:
    value: true
epochs:
    value: 20
loss:
    value: mse(proj(z_rgb), z_lidar)
lr:
    value: 0.001
pool_type:
    value: maxpool
stage:
    value: projector
task:
    value: 5
