_wandb:
    value:
        cli_version: 0.23.1
        e:
            x7ufuf79cc9f72w7cs7s8jk6h5qaua8o:
                codePath: g:\My Drive\Hands-on-CV-Project2\notebooks\04_final_assessmen.ipynb
                codePathLocal: 04_final_assessmen.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "510455517184"
                        used: "432429494272"
                email: constantin.auga@gmx.de
                executable: c:\Users\const\anaconda3\python.exe
                git:
                    commit: 34e076f07efc6a9e0684183abceddc74da09e50f
                    remote: https://github.com/Conscht/CLIP-Multimodal-Learning.git
                host: Conscht
                memory:
                    total: "16542097408"
                os: Windows-10-10.0.26100-SP0
                program: g:\My Drive\Hands-on-CV-Project2\notebooks\04_final_assessmen.ipynb
                python: CPython 3.11.4
                root: g:\My Drive\Hands-on-CV-Project2\notebooks
                startedAt: "2025-12-31T16:22:42.217855Z"
                writerId: x7ufuf79cc9f72w7cs7s8jk6h5qaua8o
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 1
                - 5
                - 53
                - 54
            "2":
                - 1
                - 5
                - 53
                - 54
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.4
            "5": 0.23.1
            "8":
                - 1
                - 3
            "12": 0.23.1
            "13": windows-amd64
encoders_frozen:
    value: true
epochs:
    value: 10
input:
    value: proj(cilp.rgb(rgb))
lr:
    value: 0.001
pool_type:
    value: maxpool
projector_frozen:
    value: true
stage:
    value: classifier
task:
    value: 5
